services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  setup:
    build: 
      context: .
      dockerfile: Dockerfile

    command:  >
      /bin/sh -c '
      chmod +x /app/setup.sh &&
      /app/setup.sh
      '
    environment:
      DJANGO_CREATED_SUPERUSER: "true"
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin 
      DJANGO_SUPERUSER_EMAIL: admin@example.com 
    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy

 